import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// The sounds the game makes while you're looking at it.
///
/// Notification sounds are a separate path — those belong to the OS channel
/// (see `PushNotifications`) and fire when the app is in your pocket. This
/// covers the case where you're already on the screen when it happens, and
/// the OS wouldn't post a notification at all.
///
/// Both sources are generated by `tools/gen_audio.sh`. See there for why the
/// frame camera is deliberately silent.
enum GameSound {
  /// The compass pulse landed: you have a bearing on your target.
  pulse('audio/pulse.mp3'),

  /// A frame photo is being revealed to the jury on the judging screen.
  ///
  /// Not the camera. Photographing your target is covert — IDEA.md is
  /// explicit that the target is never told — so a click at capture time
  /// would hand them the one tell they should never get. This is the sound
  /// of the photo reaching the people voting on it, which is public anyway.
  shutter('audio/shutter.mp3');

  const GameSound(this.asset);

  final String asset;
}

/// Plays short one-shot SFX.
abstract interface class GameSounds {
  Future<void> play(GameSound sound);
}

/// Audio here is decoration, never information: every sound accompanies
/// something already on screen, so a device on silent, a failed decode or a
/// missing asset loses nothing but polish. That's why failures are logged and
/// swallowed — an SFX must never take a screen down with it.
class AudioPlayerGameSounds implements GameSounds {
  AudioPlayerGameSounds({AudioPlayer Function()? createPlayer})
    : _createPlayer = createPlayer ?? AudioPlayer.new;

  final AudioPlayer Function() _createPlayer;

  /// One player per sound. Sharing a single player meant every play had to
  /// `stop()` first, so a judging reveal landing within ~200ms of a compass
  /// pulse chopped the pulse in half — and the pulse is the one sound
  /// carrying something a player acts on. Per-sound players only ever
  /// interrupt a repeat of themselves.
  final _players = <GameSound, AudioPlayer>{};

  Future<void>? _context;

  @override
  Future<void> play(GameSound sound) async {
    try {
      // Awaited, not fire-and-forget: setting the audio context is an async
      // platform round trip, and a pulse buffered by Realtime can arrive the
      // instant this page mounts. Playing before it lands would use
      // audioplayers' defaults — on iOS that's `playback`, which ignores the
      // silent switch, the precise opposite of the intent below.
      await (_context ??= _configureGlobalContext());
      final player = _players.putIfAbsent(sound, _createPlayer);
      await player.stop();
      await player.play(AssetSource(sound.asset));
    } on Object catch (e) {
      debugPrint('GameSounds: ${sound.name} failed to play ($e)');
    }
  }

  Future<void> _configureGlobalContext() async {
    // The three settings that matter, and why:
    //
    // `AVAudioSessionCategory.ambient` — the iOS category that honours the
    // physical silent switch and mixes with other audio instead of pausing
    // it. Note there's no `mixWithOthers` option: `ambient` already implies
    // it, and passing it explicitly trips an assert inside audioplayers
    // (audio_context.dart:177). Being an assert, that only fires in
    // debug/profile — so it would have made every build we can test here
    // behave differently from the one that ships.
    //
    // `AndroidAudioFocus.none` — this app runs a foreground location service
    // for the whole game (IDEA.md "Tech used"). Requesting focus for a 200ms
    // blip risks the OS shuffling focus mid-game, and would duck whatever
    // the player is listening to on a two-hour walk. A pulse is not worth
    // interrupting someone's music for.
    //
    // `AndroidUsageType.notification` — deliberate, and IDEA.md is why:
    // silencing your phone hides you from the pulse's tell, at the cost of
    // missing your own pulses. That trade only exists if the in-app pulse
    // obeys the same silencer the notification does. Routing it to the media
    // stream instead would let a "silenced" phone chirp anyway.
    await AudioPlayer.global.setAudioContext(
      AudioContext(
        android: const AudioContextAndroid(
          isSpeakerphoneOn: false,
          stayAwake: false,
          contentType: AndroidContentType.sonification,
          usageType: AndroidUsageType.notification,
          audioFocus: AndroidAudioFocus.none,
        ),
        iOS: AudioContextIOS(category: AVAudioSessionCategory.ambient),
      ),
    );
  }
}
